config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'pets#index'
resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true, length: { maximum: 45, minimum: 3 }
  validates :comment, presence: true, length: { maximum: 100, minimum: 10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
def index
  @pet = Pet.all
end

  def new
    @pet = Pet.new
  end 

def create
  @pet = Pet.create(pet_params)
  if @pet.invalid?
    flash[:error] = 'Could not save comment.'
  end
  redirect_to root_path
end

private

def pet_params
  params.require(:pet).permit(:name, :comment)
  

end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pets 101</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header class="row">
      <div class="col-3">
       
      </div>
      
      <div class=" col-4 offest-1">
        <div class="intro">
        Tips for New Dog Owners
      </div> 
    </div>

  </header>
  <hr />
  <br class="clear" />

<div class="container">
  <% if flash[:error].present? %>
    <div class="col-10 offset-1 alert alert-danger">
      <%= flash[:error].html_safe %>
    </div>
    <% end %>
    <%= yield %>
  </div>

  
    <div class="container">
      <div class="row">
        <div class="col-5 comment-section">
           <%= link_to 'Contribute your tips to our comment section', new_pet_path %>
     
      </div>
    </div>
  </div>

  </body>
</html>

app/views/pets/index.html.erb
<div class="footer">
    <div class="container">
<% @pet.each do |pet| %>
<div class="booyah-box col-12 col-sm-6">
  <h1><%= pet.name %></h1><br />
  <i><%= pet.comment %></i><br />
</div>
<% end %>
</div>
</div>

<h2 align="center"> Bringing home a new or dog is always exiting.
    <br> Just keep in mind you will need to learn how to build a strong foundation with your dog.
</h2>


<div class="container">
  <div class="row">
    <%= image_tag 'man_with_dog.jpg', class:'homepage-img' %>
</div>
</div>




<p>Here are the top 10 tips you need to know to become a responsible dog owner.</p>
  <ol>
    <li> Provide clean and suditable housing  </li>
    <li> Provide fresh water daily</li>
    <li> Provided quality dog food </li>
    <li> Maintain physical fitness with exercise on a daily basis </li>
    <li> Establish house rules as soon as your puppy or dog arrives home</li>
    <li> Use training and disciple techniques to create good habits </li>
    <li> Learn the basic gromming techniques for your breed</li>
    <li> Go to the vet yearly for vaccines </li>
    <li> Spay/Neuter to prevent unwanted puppies or dogs </li>
    <li> Remember to have patience and a good attitude </li>
  </ol>

app/views/pets/new.html.erb
<h1>Enter your comment below</h1>
<%= simple_form_for @pet do |f| %>
<%= f.input :name %>
<%= f.input :comment %>
<br />
<%= f.submit 'Submit' , class: 'btn btn-outline-success' %>
<% end %>